### ISSUE TITLE
Can not install use: npm install tsjs-xpx-catapult-sdk

### ISSUE THREAD

**Issue by hungtranqn** [proximax-storage/tsjs-xpx-catapult-sdk#17]
1. I install this sdk by: npm install tsjs-xpx-catapult-sdk, have error: 
```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for tsjs-xpx-catapult-sdk

npm ERR! A complete log of this run can be found in:
npm ERR!     home/.npm/_logs/2019-06-05T09_34_57_889Z-debug.log
```
2. And I try to install use: npm install https://github.com/proximax-storage/tsjs-xpx-catapult-sdk.git but have same error above
 3. When i check version in www.npmjs.com, it not exist.

Please help me, Thanks.

**Comment by yaaccount** [comment]
It is not published on npm just yet, it should be during next days. Meantime, you can try to follow this guide to use it directly from github: https://github.com/proximax-storage/tsjs-xpx-catapult-sdk/wiki/Installation-from-github. Note that the project name will probably change.

**Comment by hungtranqn** [comment]
Thank for help.
